### ISSUE TITLE
Random Number Generation Iterator Potentially Returning Non-Random Values

### ISSUE THREAD

**Issue by ericeilertson** [chipsalliance/caliptra-sw#837]
The Caliptra drivers provided an implementation of the Iterator trait which could be used
to supply a sequence of a pre-defined quantity of random numbers, produced by the
CSRNG peripheral connected to the device. Under certain conditions, this implementation
could enter a state where the supplied values could not be guaranteed to be random.

This iterator was not used by the code in a way which could lead to this condition, and as a
result this finding is being reported for informational purposes only. However, the condition
was not documented or prohibited by the iterator code, leading to the possibility that future
code might reuse the iterator code in a dangerous fashion, leading to the possibility that
random values produced by the code might be more easily guessable by an attacker

**Comment by rkr35** [comment]
As of https://github.com/chipsalliance/caliptra-sw/commit/f2c54a6f52c325a7e847d49875250c0182e6969a, the CSRNG driver no longer uses an `Iterator` implementation to yield random numbers.

The current implementation provides [functions to return fixed-sized arrays of 12 and 16 random words](https://github.com/chipsalliance/caliptra-sw/blob/9833f31724c106c72f515a05757e59b143b9daa6/drivers/src/csrng.rs#L134).

The audit notes that the former `Iterator` implementation used a backward-running counter, and it was possible to return uninitialized data by using an initial counter value that wasn't divisible by the block size (4 words).

[The current implementation uses a forward-running counter](https://github.com/chipsalliance/caliptra-sw/blob/9833f31724c106c72f515a05757e59b143b9daa6/drivers/src/csrng.rs#L169) (via [`array::from_fn`](https://doc.rust-lang.org/stable/core/array/fn.from_fn.html)), which ensures `genbits_vld()` is awaited for the first block.

A related bug in the spirit of the audit's finding is that one could still pass a not-divisible-by-four `N` into `generate()`, e.g., someone writing a `generate15()` method in the future. In this scenario, the driver would indefinitely poll `genbits_vld()` instead of returning uninitialized data.
