### ISSUE TITLE
ROM Stuck in Entropy_src StartupPhase1

### ISSUE THREAD

**Issue by ayanavachakraborty** [chipsalliance/caliptra-sw#874]
We want to enable the internal trng. We pushed 384bits of data via itrng interface. For that the rom was stuck at StartupPhase1. Next we tried 2048bits of data via itrng interface which cause the program counter to move to StartupPass1. 
Now we are sending itrng data in a loop for which the rom moved ahead.

Is this the right way to configure the itrng?

**Comment by JohnTraverAmd** [comment]
* Can you please add some waveforms?
* Can you confirm that you are compiled for iTRNG?

**Comment by howardtr** [comment]
@korran @rkr35 - do we have a rom test for this that @ayanavachakraborty can reference?

@ayanavachakraborty - are you able to provide the items that @JohnTraverAmd  mentioned?  This will help us understand the state / configuration better, thanks!

Note: pls refer to this [doc](https://opentitan.org/book/hw/ip/entropy_src/doc/theory_of_operation.html#theory-of-operation), which describes that the 384 bits are used in the initial boot-time mode to quickly seed the entropy_src.  2048 bits are required when going through the SHA-3 block

**Comment by rkr35** [comment]
Apologies for the late response.

You need to supply 4096 bits, which is two windows of 2048 bits.

See [Main State Machine Diagram](https://opentitan.org/book/hw/ip/entropy_src/doc/theory_of_operation.html#main-state-machine-diagram) for more information.

The reason you need to supply two windows is because the startup health check requires two consecutive windows to pass before advancing the state machine to the continuous phase.

**Comment by FerralCoder** [comment]
@ayanavachakraborty, can we close this issue now?

**Comment by korran** [comment]
Closing as no active on this issue; as far as we can tell the RTL and firmware handle this correctly.
